package com.miamia.ui.shared

val WAITING_PHRASES = listOf(
    "Distillation des essences en cours...",
    "Interrogatoire musclé des colorants artificiels en cours...",
    "Négociation diplomatique avec les fibres pour qu'elles restent calmes...",
    "Traduction du langage complexe des étiquettes (le 'E452' refuse de parler)...",
    "Traque intensive des calories clandestines qui tentent de se cacher...",
    "Scan moléculaire terminé : les vitamines ont l'air de bonne humeur.",
    "Tentative de corruption par un carré de chocolat détectée (et refusée)...",
    "Calcul de la vitesse à laquelle ce sucre va rejoindre vos hanches...",
    "Analyse de la relation toxique entre votre foie et ces additifs...",
    "Consultation de l'Oracle de la Nutrition (il hésite entre 'Bio' et 'Pourquoi pas ?')...",
    "Déglaçage algorithmique de vos ingrédients en cours...",
    "Nos algorithmes goûtent virtuellement chaque ligne… le verdict arrive.",
    "Les conservateurs jouent à cache-cache ; on les débusque.",
    "Prise de pouls de votre tableau nutritionnel, un instant.",
    "Les lipides préparent leur plaidoirie ; le juge délibère.",
    "Recensement des sucres qui prétendent être naturels…",
    "Lecture entre les lignes des tout petits caractères en bas d'étiquette…",
    "Arbitrage tendu entre « bon pour la ligne » et « irrésistible ».",
    "Les protéines s'étirent pendant qu'on compte les grammes.",
    "Vérification que le « sans gluten » ne cache pas d'autres surprises…",
    "La casserole des données mijote à feu doux, encore un peu de patience.",
)
